
logging:
  file: F:\logs\bsearch\app.log
  level: debug
app:
  version: 1.0
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: test
    url: jdbc:mysql://127.0.0.1:3306/bilibili
    username: root
    password: nxy
    driver-class-name: com.mysql.jdbc.Driver
