logging:
  file: F:\logs\bsearch\app.log
  level: debug
app:
  version: 1.0
  bili:
    api:
      avinfo-url: http://api.bilibili.com/archive_stat/stat
      avinfo-start: 100
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: test
    url: jdbc:mysql://127.0.0.1:3306/bilibili
    username: root
    password: nxy
    driver-class-name: com.mysql.jdbc.Driver
